apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinydeployment
  labels:
    app: eulerShiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eulerShiny
  template:
    metadata:
      labels:
        app: eulerShiny
    spec:
      containers:
      - name: eulerShiny
        image: corlua/test-shiny-euler:v2 
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: euler-service
spec:
  type: NodePort
  selector:
    app: eulerShiny
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
