apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinydeployment
  labels:
    app: eulershiny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eulershiny
  template:
    metadata:
      labels:
        app: eulershiny
    spec:
      containers:
      - name: eulershiny
        image: corlua/test-shiny-euler:v2 
        ports:
        - containerPort: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: euler-service
spec:
  type: LoadBalancer
  selector:
    app: eulershiny
  ports:
    - protocol: TCP
      port: 3838
      targetPort: 3838
