kind: Service
apiVersion: v1
metadata:
  name: shinyproxy
  namespace: alperin-corsuz-dev
spec:
  type: LoadBalancer
  selector:
    run: shinyproxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
