kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: alperin-corsuz-dev
  name: service-all
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy-auth
subjects:
  - kind: ServiceAccount
    name: alperin-corsuz-dev
    namespace: alperin-corsuz-dev
roleRef:
  kind: Role
  name: service-all
  apiGroup: rbac.authorization.k8s.io
