kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: alperin-corsuz-dev
  name: masterrole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shinyproxy-rolebinding
subjects:
  - kind: ServiceAccount
    name: alperin-corsuz-dev
    namespace: alperin-corsuz-dev
roleRef:
  kind: Role
  name: masterrole
  apiGroup: rbac.authorization.k8s.io
